apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zenithrapps.zenithr.kiegroup.org
spec:
  group: zenithr.kiegroup.org
  names:
    kind: ZenithrApp
    listKind: ZenithrAppList
    plural: zenithrapps
    singular: zenithrapp
  scope: Namespaced
  version: v1
  subresources:
    status: {}
