apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: zenithr-operator
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: null
    name: zenithr-operator
  rules:
    - apiGroups:
        - ""
      resources:
        - pods
        - services
        - endpoints
        - persistentvolumeclaims
        - events
        - configmaps
        - secrets
      verbs:
        - '*'
    - apiGroups:
        - ""
      resources:
        - namespaces
      verbs:
        - get
    - apiGroups:
        - apps
      resources:
        - deployments
        - daemonsets
        - replicasets
        - statefulsets
      verbs:
        - '*'
    - apiGroups:
        - monitoring.coreos.com
      resources:
        - servicemonitors
      verbs:
        - get
        - create
    - apiGroups:
        - route.openshift.io
      resources:
        - '*'
      verbs:
        - '*'
    - apiGroups:
        - zenithr.kiegroup.org
      resources:
        - '*'
      verbs:
        - '*'
- kind: RoleBinding
  apiVersion: rbac.authorization.k8s.io/v1
  metadata:
    name: zenithr-operator
  subjects:
    - kind: ServiceAccount
      name: zenithr-operator
  roleRef:
    kind: Role
    name: zenithr-operator
    apiGroup: rbac.authorization.k8s.io
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: zenithr-operator
  spec:
    replicas: 1
    selector:
      matchLabels:
        name: zenithr-operator
    template:
      metadata:
        labels:
          name: zenithr-operator
      spec:
        serviceAccountName: zenithr-operator
        containers:
          - name: zenithr-operator
            # Replace this with the built image name
            image: quay.io/kiegroup/zenithr-operator
            command:
              - zenithr-operator
            imagePullPolicy: Always
            env:
              - name: WATCH_NAMESPACE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: POD_NAME
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: OPERATOR_NAME
                value: "zenithr-operator"
